### PR TITLE
Added error messages

### PR DESCRIPTION
**Pull request by NihalNavath**
Improved UX, Added error message that are shown to user, if username or address in the connect page are invalid.

Note: Only client side checks were added, need to add server checks as user can easily change the js on the client side to remove the checks.

Some examples:

image
image1

### CODE REVIEW

**Comment by Viswas-Programs** [comment]
one issue with this commit, is that if i enter a wrong localhost port, like, instead of localhost:8080, if I enter localhost:9870 or random number, it doesn't recognize that, and doesn't give me an error.
I tested it, and it didn't work
The others worked fine. (like the 50 char limit, invalid username and thing like that)

**Comment by NihalNavath** [comment]
It only checks the validity of the address using regex, doesn't actually check if the web socket exists, if you want to add that this this line where I commented.

**Comment by Viswas-Programs** [comment]
And also, I am not able to specify IP Address in the server address.
Is there anything I could do about that, to specify IP Address?

**Comment by NihalNavath** [comment]
It should also accept IP addresses, is there an IP address that fails for you? Show me the address.

**Comment by Viswas-Programs** [comment]
192.168.29.147:8080 I try to use this
But it says: Invalid Address

**Comment by NihalNavath** [comment]
> 192.168.29.147:8080 I try to use this
> 
> But it says: Invalid Address

Hmm rn it only accepts IP address not ip + port, guess will change that behaviour. Also if your running client and server on the same device you can just use localhos

**Comment by Viswas-Programs** [comment]
I can use localhost, ik.
But, I tested this situation, since I have my PC and my family PC , and I used my family PC as the server, and I as the client, would access it, from my PC.
And btw, I saw it accepts Raw IP addresses (like without port), but, if that's the case, in the inspect console, it gives an error connecting to that address.
So, please fix that issue.

**Comment by NihalNavath** [comment]
> I can use localhost, ik.
> 
> But, I tested this situation, since I have my PC and my family PC , and I used my family PC as the server, and I as the client, would access it, from my PC.
> 
> And btw, I saw it accepts Raw IP addresses (like without port), but, if that's the case, in the inspect console, it gives an error connecting to that address.
> 
> So, please fix that issue. 

Try running server on port 80

**Comment by Viswas-Programs** [comment]
Did you make any changes to the code? You haven't commited to your repo yet, so I can't access the changes!

**Comment by NihalNavath** [comment]
> Did you make any changes to the code? You haven't commited to your repo yet, so I can't access the changes!

No changes http uses port 80 by default iirc, so try running the server on port 80

**Comment by Viswas-Programs** [comment]
Oh yeah, that works bro, thanks for the info, so now, I should include the server port changes in the opensurviv-server repo, because that uses default port as 8080, not 80.
I will make sure to include the changes in the repo, in my upcoming pull request.

**Pull request merged**
